#!/bin/bash

#cd to folder where the data are
# cd /storage/shared/research/cinn/2018/MLCTBS/Test
cd /storage/shared/research/cinn/2018/GABAVB/BIDS/

# load the fsl module
module load fsl6.0

echo "MT analysis"
# here we need to add the subject numbers
#for i in 00101	00102	00103	00201	00202	00203	00301	00302	00303	00401	00402	00403	00501	00502	00503	00601	00602	00603	00701	00702	00703	00801	00802	00803	00901	00902	00903	01001	01002	01003	0011	01102	01103	01201	01202	01203	01302	01303	01401	01403	01501	01601	01602	01603	01901	01902	01903	02101	02102	02103	0022	02202	02203	0023	02302	02303	0035	03502	03503	0036	03602	03603	0037	03702	03703	0038	03802	03803	0040	04002	04003	0041	04102	04103	0042	04202	04203	0043	04302	04303

for i in 01401	01601	01901	02102	02103	0022	02202	02203	0023	02302	02303	0035	03502	03503	0036	03602	0037	03702	03703	0038	03802	03803	0040	04002	04003	0041	04102	04103	0042	0043

	do

	# cd to the anat folder of the subject
	cd sub-${i}/anat/

	# print in the terminal the path
	echo $PWD

	# print the starting statement
	echo "starting sub-${i}"

	# check if the brain extracted FLASH file is present in the folder
	if [ ! -f sub-"${i}"_rec-NORM_T1w_brain* ]; then
		# print the statement if the brain extracted FLASH file is found
		echo "T1w_brain not found"
		echo "starting BET"
		num=1
		for x in 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7; do
			input_volume=sub-"${i}"_rec-NORM_T1w
			output_volume=sub-"${i}"_rec-NORM_T1w_brain_${num}
			f_value="${x}"
			/usr/share/fsl/6.0/bin/bet $input_volume $output_volume -f $f_value -g 0
			echo "BET T1w with f = ${x} completed"
			# echo "opening BET"
			# fsleyes $input_volume $output_volume -cm Red-Yellow
			num=$((num+1))
			echo "startin new BET"
		done
	else
		echo "T1w_brain found, BET will not be run"
	fi
	echo -e

	# check if the brain extracted FLASH file is present in the folder
	if [ ! -f sub-"${i}"_rec-NORM_T2w_brain* ]; then
		# print the statement if the brain extracted FLASH file is found
		echo "T2w_brain not found"
		echo "starting BET"
		num=1
		for x in 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7; do
			input_volume=sub-"${i}"_rec-NORM_T2w
			output_volume=sub-"${i}"_rec-NORM_T2w_brain_${num}
			f_value="${x}"
			/usr/share/fsl/6.0/bin/bet $input_volume $output_volume -f $f_value -g 0
			echo "BET T2w with f = ${x} completed"
			# echo "opening BET"
			# fsleyes $input_volume $output_volume -cm Red-Yellow
			num=$((num+1))
			echo "startin new BET"
		done
	else
		echo "T2w_brain found, BET will not be run"
	fi
	echo -e

	# check if the brain extracted FLASH file is present in the folder
	if [ ! -f sub-"${i}"_rec-NORM_FLASH_brain* ]; then
		# print the statement if the brain extracted FLASH file is found
		echo "FLASH_brain not found"
		echo "starting BET"
		num=1
		for x in 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7; do
			input_volume=sub-"${i}"_rec-NORM_FLASH
			output_volume=sub-"${i}"_rec-NORM_FLASH_brain_${num}
			f_value="${x}"
			/usr/share/fsl/6.0/bin/bet $input_volume $output_volume -f $f_value -g 0
			echo "BET FLASH with f = ${x} completed"
			# echo "opening BET"
			# fsleyes $input_volume $output_volume -cm Red-Yellow
			num=$((num+1))
			echo "startin new BET"
		done
	else
		echo "FLASH_brain found, BET will not be run"
	fi
	echo -e

	# check if the brain extracted FLASH file is present in the folder
	if [ ! -f sub-"${i}"_rec-NORM_T1map_brain* ]; then
		# print the statement if the brain extracted FLASH file is found
		echo "T1map_brain not found"
		echo "starting BET"
		num=1
		for x in 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7; do
			input_volume=sub-"${i}"_rec-NORM_T1map
			output_volume=sub-"${i}"_rec-NORM_T1map_brain_${num}
			f_value="${x}"
			/usr/share/fsl/6.0/bin/bet $input_volume $output_volume -f $f_value -g 0
			echo "BET T1map with f = ${x} completed"
			# echo "opening BET"
			# fsleyes $input_volume $output_volume -cm Red-Yellow
			num=$((num+1))
			echo "startin new BET"
		done
	else
		echo "T1map_brain found, BET will not be run"
	fi
	echo -e



	# cd back to the BIDS folder
	cd ../..

done
