#!/bin/bash

#cd to folder where the data are
cd /storage/shared/research/cinn/2018/GABAVB/BIDS/

# load the fsl module
module load fsl6.0

echo "T1w/T2w analysis - GROUP"
# here we need to add the subject numbers
for i in 00101	00102	00103	00201	00202	00203	00301	00302	00303	00401	00402	00403	00501	00502	00503	00601	00602	00603	00701	00702	00703	00801	00802	00803	00901	00902	00903	01001	01002	01003	0011	01102	01103	01201	01202	01203	01301	01302	01303	01401	01403	01501	01502	01601	01602	01603	01901	01902	01903	02101	02102	02103	0022	02202	02203	0023	02302	02303	0035	03502	03503	0036	03602	0037	03702	03703	0038	03802	03803	0040	04002	04003	0041	04102	04103	0042	04202	04203	0043	04302	04303

	do

	# cd to the anat folder of the subject
	cd sub-${i}/anat/

	# print in the terminal the path
	echo $PWD

	# print the starting statement
	echo "starting sub-${i}"

	# check if the brain extracted FLASH file is present in the folder
	if [ -f sub-"${i}"_rec-NORM_FLASH_brain.nii.gz ]; then
		# print the statement if the brain extracted FLASH file is found
		echo "FLASH_brain found"
		# assign the file to the variable 'flash_volume'
		flash_volume=sub-"${i}"_rec-NORM_FLASH_brain.nii.gz

		# check if the brain extracted T1map is present in the folder
		if [ -f sub-"${i}"_rec-NORM_T1map_brain.nii.gz ]; then
			# print the statement if the brain extracted T1map is found
			echo "T1map_brain found"
			# assign the file to the variable 'MT_volume'
			MT_volume=sub-"${i}"_rec-NORM_T1map_brain.nii.gz
			# creating the name for the subtraction volume
			subtraction_volume=sub-"${i}"-MTR_subtraction.nii.gz
			# creating the name for the division volume
			division_volume=sub-"${i}"-MTR_division.nii.gz
			# creating the name for the final MRT
			MRT_volume=sub-"${i}"-MTR_final.nii.gz

			echo "STEP1: generating MTR"
			# computing the difference between FLASH and T1map and saving it in
			# subtraction_volume
			fslmaths $flash_volume -sub $MT_volume $subtraction_volume
			# when subtraction is done, print it in the terminal
			echo "subtraction completed"

			# computing the division between subtraction_volume and FLASH, and
			# saving it in division_volume
			fslmaths $subtraction_volume -div $flash_volume $division_volume
			# when division is done, print it in the terminal
			echo "division completed"

			# multiplying the division_volume by 100 and saving it in MRT_volume
			fslmaths  $division_volume -mul 100 $MRT_volume
			# when multiplication is done, print it in the terminal
			echo "multiplication completed"
			echo "MTR generated"
			echo -e

			# check if the brain extracted T1w is present in the folder
			if [ -f sub-"${i}"_rec-NORM_T1w_brain.nii.gz ]; then
				echo "STEP2: registration of MTR to T1w_brain"
				echo "starting registration of MTR to T1w_brain"
				input_mtr_to_t1=sub-"${i}"-MTR_final.nii.gz
				ref_mtr_to_t1=sub-"${i}"_rec-NORM_T1w_brain.nii.gz
				output_mtr_to_t1=sub-"${i}"-MTR_to_T1w.nii.gz
				mat_mtr_to_t1=sub-"${i}"-MTR_to_T1w.mat

/usr/share/fsl/6.0/bin/flirt -in $input_mtr_to_t1 -ref $ref_mtr_to_t1 -out $output_mtr_to_t1 -omat $mat_mtr_to_t1 -bins 256 -cost corratio -searchrx 0 0 -searchry 0 0 -searchrz 0 0 -dof 6  -interp nearestneighbour
				echo "registration of MTR to T1w_brain completed"
				echo -e

				echo "STEP3: registration of T1w_brain to MNI152_2mm and co-registration of MT_to_T1w to MNI152_1mm"
				input_t1_to_mni=sub-"${i}"_rec-NORM_T1w_brain.nii.gz
				ref_mni=/usr/share/fsl/6.0/data/standard/MNI152_T1_1mm_brain
				output_t1_to_mni=sub-"${i}"_rec-NORM_T1w_brain_to_mni.nii.gz
				output_mtr_to_mni=sub-"${i}"-MTR_to_MNI.nii.gz
				mat_t1_to_mni=sub-"${i}"_rec-NORM_T1w_brain_to_mni.mat
				echo "starting registration of T1w_brain to MNI152_2mm"
/usr/share/fsl/6.0/bin/flirt -in $input_t1_to_mni -ref $ref_mni  -out $output_t1_to_mni -omat $mat_t1_to_mni -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 6  -interp nearestneighbour

				echo "registration of T1w to MNI152_2mm completed"
				echo "starting co-registration of MT_to_T1w to MNI152_1mm"
/usr/share/fsl/6.0/bin/flirt -in $output_mtr_to_t1 -ref $ref_mni -out $output_mtr_to_mni -applyxfm -init $mat_t1_to_mni -interp nearestneighbour

				echo "co-registration of MT_to_T1w to MNI152_2mm completed"
				echo -e

				# this was the last step, print in the terminal that we're done with
				# this participant
				echo "sub-${i} finished"
				echo -e
			else
			echo "T1w_brain not found"
			echo -e
			echo "MT aborted"
			fi

		else
		echo "T1map_brain not found"
		echo -e
		echo "MT aborted"
		fi

	else
	echo "FLASH_brain not found"
	echo -e
	echo "MT aborted"
	fi

	# cd back to the BIDS folder
	cd ../..

done
