#!/bin/bash

source ~/.bashrc
#cd to folder where the data are
cd /storage/shared/research/cinn/2018/GABAVB/T1w_T2w_ratio/PVE_2/1mm

# print in the terminal the path
echo $PWD
echo -e

cd Day1-Day2/
echo "start DAY1-DAY2"
echo -e

cd B12

echo "start B12 group"
echo -e
echo $PWD
randomise -i RATIO_PVE_2_B12_DAY1_DAY2_1mm -o RATIO_PVE_2_B12_DAY1_DAY2_1mm_PairedT -d RATIO_PVE2_B12_DAY1_DAY2_1mm.mat -t RATIO_PVE2_B12_DAY1_DAY2_1mm.con -e RATIO_PVE2_B12_DAY1_DAY2_1mm.grp -T 


