#!/bin/bash


#cd to folder where the data are
cd /storage/shared/research/cinn/2018/GABAVB/T1w_T2w_ratio/PVE_1/1mm

# print in the terminal the path
echo $PWD
echo -e

cd Day1-Day2/

echo "start DAY1-DAY2"
echo -e

cd PLACEBO

echo "start PLACEBO group"
echo -e
echo $PWD
randomise -i RATIO_PVE_1_PLACEBO_DAY1_DAY2_1mm -o RATIO_PVE_1_PLACEBO_DAY1_DAY2_1mm_PairedT -d RATIO_PVE1_PLACEBO_DAY1_DAY2_1mm.mat -t RATIO_PVE1_PLACEBO_DAY1_DAY2_1mm.con -e RATIO_PVE1_PLACEBO_DAY1_DAY2_1mm.grp -T 
cd ..

echo "done"
echo -e

cd B12
echo "start B12 group"
echo -e
echo $PWD
#randomise -i RATIO_PVE_1_B12_DAY1_DAY2_1mm -o RATIO_PVE_1_B12_DAY1_DAY2_1mm_PairedT -d RATIO_PVE1_B12_DAY1_DAY2_1mm.mat -t RATIO_PVE1_B12_DAY1_DAY2_1mm.con -e RATIO_PVE1_B12_DAY1_DAY2_1mm.grp -T 

echo "done"
echo -e

cd /storage/shared/research/cinn/2018/GABAVB/T1w_T2w_ratio/PVE_1/1mm/Day2-Day3/

echo "start DAY2-DAY3"
echo -e

cd PLACEBO
echo "start PLACEBO group"
echo -e
echo $PWD
randomise -i RATIO_PVE_1_PLACEBO_DAY2_DAY3_1mm -o RATIO_PVE_1_PLACEBO_DAY2_DAY3_1mm_PairedT -d RATIO_PVE1_PLACEBO_DAY2_DAY3_1mm.mat -t RATIO_PVE1_PLACEBO_DAY2_DAY3_1mm.con -e RATIO_PVE1_PLACEBO_DAY2_DAY3_1mm.grp -T
cd ../

echo "done"
echo -e

cd B12
echo "start B12 group"
echo -e
echo $PWD
randomise -i RATIO_PVE_1_B12_DAY2_DAY3_1mm -o RATIO_PVE_1_B12_DAY2_DAY3_1mm_PairedT -d RATIO_PVE1_B12_DAY2_DAY3_1mm.mat -t RATIO_PVE1_B12_DAY2_DAY3_1mm.con -e RATIO_PVE1_B12_DAY2_DAY3_1mm.grp -T 
echo "done"
echo -e


